### ISSUE TITLE
Problème de compréhension et suggestion pour le script

### ISSUE THREAD

**Issue by Doll293** [Dan-Popescu/terminal_commands#2]
# Réponse 

**Is your feature request related to a problem? Please describe.**
J'ai un peu du mal comprendre ce que tu veux dire : 
``git fork https://github.com/yourusername/linux-windows-project.git``

![image](https://github.com/Dan-Popescu/terminal_commands/assets/126485056/6f98375d-c2a5-4f8b-82c6-63750c0bc8b1)

![image](https://github.com/Dan-Popescu/terminal_commands/assets/126485056/5d58db93-2995-41d7-aaf0-b784aa6cea1a)

**Describe the solution you'd like**
Ajouter des commandes : 
- "exec" pour executer des scripts
- "rm" pour supprimer des fichiers
- "touch" pour ajouter des fichiers

**Comment by Dan-Popescu** [comment]
Bonjour, 
Merci pour tes suggestions. Le problème que tu a identifié n'est pas lié aux solutions proposées comme feature. Pourrais-tu fermer ce ticket et en réouvrir 2 autres : 1 issue de type Bug Report pour le problème que tu rencontres et un 2ème issue de type Feature Request pour les features proposées.
