### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Doll293** [Dan-Popescu/terminal_commands#4]
**Describe the solution you'd like**
Ajouter des commandes : 
- "exec" pour executer des scripts
- "rm" pour supprimer des fichiers
- "touch" pour ajouter des fichiers

**Comment by Dan-Popescu** [comment]
Bonjour,

Merci pour ses suggestions. Je pense que c'est une bonne idée pour que ces commandes soient les suivantes à implémenter étant donnée la fréquence de leur usage.

**Comment by Doll293** [comment]
j'ai implémenter les commandes touch et rm

**Comment by Dan-Popescu** [comment]
Merci pour ta contribution.
